### ISSUE TITLE
Snap support

### ISSUE THREAD

**Issue by baimafeima** [v2ray/v2ray-core#704] opened 2017-11-12 18:02 UTC
Could you provide a snap package for easy deployment on a server? Do you provide installation instructions in English how to install it on a server?

**Comment by DarienRaymond** [comment] 2017-11-12 19:59
Snap package is on the way. However, English translation for installation and setup instructions may take a long time. Your best chance for now is Google Translator.

**Comment by baimafeima** [comment] 2017-11-12 23:33
Great to know that snaps are on the roadmap.

**Comment by DarienRaymond** [comment] 2017-12-01 15:04
Closing this issue as it is not a bug. You may submit another issue at [v2ray/Planning](https://github.com/v2ray/Planning) if you want to discuss more detail on the snap packages.

**Closed by DarienRaymond** 2017-12-01 15:04 UTC
