### ISSUE TITLE
About using proxifier, mstsc will disconnect within a few minutes

### ISSUE THREAD

**Issue by asasuou** [v2ray/v2ray-core#52] opened 2015-10-29 11:52 UTC
Envirment:
v2ray version:v0.91 OS:Windows8.1

Description:
It seems that it will disconnect within a few minutes(~30 minutes not yet).
The following error message will display many times before the connection lost.

Error message:
[Error]VMessOut: Failed to read VMess response (0 bytes): read tcp 192.168.1.2:9
388->{serverip:port}: wsarecv: A connection attempt failed because the connect
ed party did not properly respond after a period of time, or established connect
ion failed because connected host has failed to respond.

**Comment by v2ray** [comment] 2015-10-29 13:43
According to offline discussion, this issue is (probably) caused by the timeout setting on V2Ray server. VMess inbound connection times out after 2 minutes waiting for client payload. MSTSC probably wants to keep a TCP connection, but doesn't send any data during the 2 minutes.

The 2-minute setting is design to mitigate DoS attack from untrusted user by not closing TCP connection in time. A solution for this issue could be letting server trust a particular user id.

**Comment by v2ray** [comment] 2015-11-03 09:54
46c0d457d99c1657fdc3e5f5c880ff1f73adb605 introduces settings per user level. You can now set user level > 0 to avoid the 2-minute timeout.

**Closed by v2ray** 2015-11-03 09:54 UTC
Labels: bug
